package state

import (
	"context"
	"fmt"
	"time"
)

// All lease timestamps are generated by SQLite itself via strftime with a
// fixed-width millisecond format ("YYYY-MM-DDTHH:MM:SS.SSSZ"), so expiry
// comparisons are lexicographic comparisons of uniform database-time strings —
// a replica's skewed process clock never participates. The format is a strict
// subset of RFC 3339, so parseSQLiteTime reads it back unchanged.
const sqliteLeaseNow = `strftime('%Y-%m-%dT%H:%M:%fZ', 'now')`

const sqliteLeaseColumns = `name, holder, fence, acquired_at, renewed_at, expires_at`

// sqliteLeaseTTLModifier renders a signed duration as an SQLite date modifier
// with millisecond precision, matching the stored timestamp resolution.
// Negative durations yield a "-N.NNN seconds" modifier, used by ReleaseLease
// to compute an already-past expiry.
func sqliteLeaseTTLModifier(ttl time.Duration) string {
	return fmt.Sprintf("%+.3f seconds", ttl.Seconds())
}

func (s *SQLiteStore) AcquireLease(ctx context.Context, name, holder string, ttl time.Duration) (Lease, bool, error) {
	ctx, err := activeContext(ctx)
	if err != nil {
		return Lease{}, false, err
	}
	name, holder, err = normalizeLeaseKey(name, holder)
	if err != nil {
		return Lease{}, false, err
	}
	if err := validateLeaseTTL(ttl); err != nil {
		return Lease{}, false, err
	}

	// One atomic upsert: insert a fresh lease at fence 1, or take over an
	// expired row at the previous fence + 1. There is intentionally no holder
	// self-reacquire clause — fence-checked RenewLease is the only extension
	// path. The retry loop covers the rare window where the upsert loses but
	// the winning row vanishes (release only tombstones, so out-of-band
	// pruning) before the loser reads it back; after the attempts are
	// exhausted the caller simply observes "not acquired" and polls again.
	acquire := `INSERT INTO ouvrier_leases (` + sqliteLeaseColumns + `)
		VALUES (?, ?, 1, ` + sqliteLeaseNow + `, ` + sqliteLeaseNow + `, strftime('%Y-%m-%dT%H:%M:%fZ', 'now', ?))
		ON CONFLICT(name) DO UPDATE SET
			holder = excluded.holder,
			fence = ouvrier_leases.fence + 1,
			acquired_at = excluded.acquired_at,
			renewed_at = excluded.renewed_at,
			expires_at = excluded.expires_at
		WHERE ouvrier_leases.expires_at < ` + sqliteLeaseNow + `
		RETURNING ` + sqliteLeaseColumns
	for attempt := 0; attempt < leaseAcquireAttempts; attempt++ {
		row := s.db.QueryRowContext(ctx, acquire, name, holder, sqliteLeaseTTLModifier(ttl))
		lease, err := scanSQLiteLease(row)
		if err == nil {
			return lease, true, nil
		}
		if !missingSQLiteRow(err) {
			return Lease{}, false, err
		}
		current, ok, err := s.leaseByName(ctx, name)
		if err != nil {
			return Lease{}, false, err
		}
		if ok {
			return current, false, nil
		}
	}
	return Lease{}, false, nil
}

func (s *SQLiteStore) RenewLease(ctx context.Context, name, holder string, fence uint64, ttl time.Duration) (Lease, bool, error) {
	ctx, err := activeContext(ctx)
	if err != nil {
		return Lease{}, false, err
	}
	name, holder, err = normalizeLeaseKey(name, holder)
	if err != nil {
		return Lease{}, false, err
	}
	if err := validateLeaseTTL(ttl); err != nil {
		return Lease{}, false, err
	}

	row := s.db.QueryRowContext(ctx, `UPDATE ouvrier_leases SET
			renewed_at = `+sqliteLeaseNow+`,
			expires_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now', ?)
		WHERE name = ? AND holder = ? AND fence = ?
		RETURNING `+sqliteLeaseColumns,
		sqliteLeaseTTLModifier(ttl), name, holder, int64(fence))
	lease, err := scanSQLiteLease(row)
	if missingSQLiteRow(err) {
		current, _, err := s.leaseByName(ctx, name)
		if err != nil {
			return Lease{}, false, err
		}
		return current, false, nil
	}
	if err != nil {
		return Lease{}, false, err
	}
	return lease, true, nil
}

func (s *SQLiteStore) ReleaseLease(ctx context.Context, name, holder string, fence uint64) error {
	ctx, err := activeContext(ctx)
	if err != nil {
		return err
	}
	name, holder, err = normalizeLeaseKey(name, holder)
	if err != nil {
		return err
	}

	// Tombstone instead of delete: expire the lease in place by database time,
	// keeping the row (holder and fence included) so the next acquire is a
	// takeover at fence + 1 and fences stay strictly monotonic per name.
	_, err = s.db.ExecContext(ctx,
		`UPDATE ouvrier_leases SET expires_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now', ?)
			WHERE name = ? AND holder = ? AND fence = ?`,
		sqliteLeaseTTLModifier(-time.Second), name, holder, int64(fence))
	return err
}

func (s *SQLiteStore) Leases(ctx context.Context) ([]Lease, error) {
	ctx, err := activeContext(ctx)
	if err != nil {
		return nil, err
	}

	rows, err := s.db.QueryContext(ctx,
		`SELECT `+sqliteLeaseColumns+` FROM ouvrier_leases ORDER BY name`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	leases := []Lease{}
	for rows.Next() {
		lease, err := scanSQLiteLease(rows)
		if err != nil {
			return nil, err
		}
		leases = append(leases, lease)
	}
	return leases, rows.Err()
}

func (s *SQLiteStore) leaseByName(ctx context.Context, name string) (Lease, bool, error) {
	row := s.db.QueryRowContext(ctx,
		`SELECT `+sqliteLeaseColumns+` FROM ouvrier_leases WHERE name = ?`, name)
	lease, err := scanSQLiteLease(row)
	if missingSQLiteRow(err) {
		return Lease{}, false, nil
	}
	if err != nil {
		return Lease{}, false, err
	}
	return lease, true, nil
}

func scanSQLiteLease(row sqlRowScanner) (Lease, error) {
	var lease Lease
	var fence int64
	var acquiredAt, renewedAt, expiresAt string
	if err := row.Scan(&lease.Name, &lease.Holder, &fence, &acquiredAt, &renewedAt, &expiresAt); err != nil {
		return Lease{}, err
	}
	lease.Fence = uint64(fence)
	var err error
	if lease.AcquiredAt, err = parseSQLiteTime(acquiredAt); err != nil {
		return Lease{}, err
	}
	if lease.RenewedAt, err = parseSQLiteTime(renewedAt); err != nil {
		return Lease{}, err
	}
	if lease.ExpiresAt, err = parseSQLiteTime(expiresAt); err != nil {
		return Lease{}, err
	}
	return lease, nil
}
