package cli

import (
	"context"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

// dockerConfig captures resolved options for `ouvrier deploy docker`.
type dockerConfig struct {
	Dir   string
	Image string
	Tag   string
	Push  bool
	Force bool
}

// dockerRunner abstracts `docker` invocations so tests can substitute a fake
// without ever touching the docker daemon.
type dockerRunner interface {
	Run(ctx context.Context, dir string, args []string, stdout, stderr io.Writer) error
}

func (app *App) runDeployDockerCommand(ctx context.Context, args []string) error {
	if hasHelpFlag(args) {
		printDeployDockerHelp(app.out)
		return nil
	}
	cfg, err := parseDeployDockerFlags(args)
	if err != nil {
		return err
	}
	return runDeployDocker(ctx, cfg, app.out, app.errOut, defaultDockerRunner{})
}

func parseDeployDockerFlags(args []string) (dockerConfig, error) {
	cfg := dockerConfig{Dir: "."}
	i := 0
	for i < len(args) {
		arg := args[i]
		switch {
		case arg == "--image":
			value, advance, err := flagValue(args, i, "--image")
			if err != nil {
				return dockerConfig{}, err
			}
			cfg.Image = value
			i += advance
		case strings.HasPrefix(arg, "--image="):
			cfg.Image = strings.TrimPrefix(arg, "--image=")
			i++
		case arg == "--tag":
			value, advance, err := flagValue(args, i, "--tag")
			if err != nil {
				return dockerConfig{}, err
			}
			cfg.Tag = value
			i += advance
		case strings.HasPrefix(arg, "--tag="):
			cfg.Tag = strings.TrimPrefix(arg, "--tag=")
			i++
		case arg == "--dir":
			value, advance, err := flagValue(args, i, "--dir")
			if err != nil {
				return dockerConfig{}, err
			}
			cfg.Dir = value
			i += advance
		case strings.HasPrefix(arg, "--dir="):
			cfg.Dir = strings.TrimPrefix(arg, "--dir=")
			i++
		case arg == "--push":
			cfg.Push = true
			i++
		case arg == "--force":
			cfg.Force = true
			i++
		default:
			return dockerConfig{}, fmt.Errorf("%w: deploy docker does not accept argument %q", ErrUsage, arg)
		}
	}
	if cfg.Dir == "" {
		cfg.Dir = "."
	}
	return cfg, nil
}

func runDeployDocker(ctx context.Context, cfg dockerConfig, out, errOut io.Writer, runner dockerRunner) error {
	if ctx == nil {
		ctx = context.Background()
	}
	if runner == nil {
		return fmt.Errorf("%w: docker runner is nil", ErrDeploy)
	}

	dir, err := filepath.Abs(cfg.Dir)
	if err != nil {
		return fmt.Errorf("%w: resolve project directory: %w", ErrDeploy, err)
	}

	pipPath := filepath.Join(dir, "pip.yaml")
	pipData, err := os.ReadFile(pipPath)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return fmt.Errorf("%w: %s not found; run this command from an Ouvrier project", ErrDeploy, pipPath)
		}
		return fmt.Errorf("%w: read pip.yaml: %w", ErrDeploy, err)
	}

	projectName, err := parsePipName(pipData)
	if err != nil {
		return fmt.Errorf("%w: %w", ErrDeploy, err)
	}

	summary := parsePipYAML(string(pipData))

	image := cfg.Image
	if image == "" {
		image = projectName
	}
	tag := cfg.Tag
	if tag == "" {
		if summary.Version != "" {
			tag = summary.Version
		} else {
			tag = "latest"
		}
	}
	ref := image + ":" + tag

	// 1. Generate (or refuse to overwrite) the Dockerfile.
	dockerfilePath := filepath.Join(dir, "Dockerfile")
	if _, statErr := os.Stat(dockerfilePath); statErr == nil {
		if !cfg.Force {
			return fmt.Errorf("%w: %s already exists; pass --force to overwrite", ErrDeploy, dockerfilePath)
		}
	} else if !errors.Is(statErr, os.ErrNotExist) {
		return fmt.Errorf("%w: stat Dockerfile: %w", ErrDeploy, statErr)
	}

	dockerfile := renderDockerfile(projectName)
	if err := os.WriteFile(dockerfilePath, []byte(dockerfile), 0o644); err != nil {
		return fmt.Errorf("%w: write Dockerfile: %w", ErrDeploy, err)
	}
	fmt.Fprintf(out, "wrote %s\n", dockerfilePath)

	// 2. Build the image.
	fmt.Fprintf(out, "docker build -t %s .\n", ref)
	if err := runner.Run(ctx, dir, []string{"build", "-t", ref, "."}, out, errOut); err != nil {
		return fmt.Errorf("%w: docker build: %w", ErrDeploy, err)
	}

	// 3. Optional push.
	if cfg.Push {
		fmt.Fprintf(out, "docker push %s\n", ref)
		if err := runner.Run(ctx, dir, []string{"push", ref}, out, errOut); err != nil {
			return fmt.Errorf("%w: docker push: %w", ErrDeploy, err)
		}
	}

	fmt.Fprintf(out, "built %s\n", ref)
	return nil
}

// renderDockerfile returns the two-stage distroless Dockerfile contents for
// the given project name. Kept separate so tests can assert on the exact
// COPY/ENTRYPOINT lines.
func renderDockerfile(projectName string) string {
	return fmt.Sprintf(`# Generated by ouvrier deploy docker. Two-stage build producing a
# distroless image. Re-run with --force to regenerate.
FROM golang:1.25 AS build
WORKDIR /src
COPY . .
RUN CGO_ENABLED=0 go build -o /out/%s ./...

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=build /out/%s /%s
ENTRYPOINT ["/%s"]
`, projectName, projectName, projectName, projectName)
}

// defaultDockerRunner shells out to the docker CLI in the project directory.
type defaultDockerRunner struct{}

func (defaultDockerRunner) Run(ctx context.Context, dir string, args []string, stdout, stderr io.Writer) error {
	cmd := newExecCommand(ctx, "docker", args)
	cmd.Dir = dir
	cmd.Stdout = stdout
	cmd.Stderr = stderr
	return cmd.Run()
}
