package scaffold

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func mainGo(cfg Config) string {
	replyType := ""
	if cfg.trigger.usesReplyType {
		replyType = "\ntype ticketReply struct {\n\tStatus string `json:\"status\"`\n}\n"
	}
	return fmt.Sprintf(`package main

import (
	"log"
	"os"

	ovr %q
)
%s
func listenAddr() string {
	if addr := os.Getenv("OUVRIER_ADDR"); addr != "" {
		return addr
	}
	return ":8080"
}

func main() {
	if err := ovr.Run(listenAddr(),
		ovr.From(%s),
		ovr.Pipe("Handle the event and return a concise status.",
			ovr.Model(%q),
		),
		%s,
	); err != nil {
		log.Fatal(err)
	}
}
`, cfg.FrameworkModule, replyType, cfg.trigger.fromArg, cfg.Model, cfg.trigger.terminalExpr)
}

func goMod(cfg Config) string {
	body := fmt.Sprintf(`module %s

go 1.25.0

require %s v0.0.0
`, cfg.Name, cfg.FrameworkModule)
	if requirements := frameworkRequireBlocks(cfg); requirements != "" {
		body += "\n" + requirements
	}
	if cfg.FrameworkDir != "" {
		body += fmt.Sprintf(`
replace %s => %s
`, cfg.FrameworkModule, cfg.FrameworkDir)
	}
	return body
}

func frameworkRequireBlocks(cfg Config) string {
	if cfg.FrameworkDir == "" {
		return ""
	}
	data, err := os.ReadFile(filepath.Join(cfg.FrameworkDir, "go.mod"))
	if err != nil {
		return ""
	}

	var blocks []string
	lines := strings.Split(string(data), "\n")
	for i := 0; i < len(lines); i++ {
		line := strings.TrimSpace(lines[i])
		switch {
		case strings.HasPrefix(line, "require ("):
			var block []string
			for ; i < len(lines); i++ {
				block = append(block, lines[i])
				if strings.TrimSpace(lines[i]) == ")" {
					break
				}
			}
			blocks = append(blocks, strings.Join(block, "\n"))
		case strings.HasPrefix(line, "require "):
			blocks = append(blocks, lines[i])
		}
	}
	return strings.Join(blocks, "\n\n")
}

func pipYAML(cfg Config) string {
	return fmt.Sprintf(`name: %s
version: 0.1.0

deploy:
  ssh:
    host: ops@example.com
    path: /opt/%s
    service: %s.service
    healthcheck:
      path: /admin/health
      timeout: 30s
  docker:
    image: %s:0.1.0
    base: gcr.io/distroless/static-debian12

env:
%s

healthcheck:
  path: /admin/health
  interval: 30s
`, cfg.Name, cfg.Name, cfg.Name, cfg.Name, envYAML(cfg))
}

func envYAML(cfg Config) string {
	env := requiredEnvVars(cfg)
	if len(env) == 0 {
		return "  required: []"
	}
	var b strings.Builder
	b.WriteString("  required:\n")
	for _, key := range env {
		b.WriteString("    - ")
		b.WriteString(key)
		b.WriteByte('\n')
	}
	return strings.TrimRight(b.String(), "\n")
}

type workerManifest struct {
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Events      []string `json:"events"`
	Outcomes    []string `json:"outcomes"`
	AdminURL    string   `json:"admin_url"`
}

func workerManifestJSON(cfg Config) string {
	manifest := workerManifest{
		Name:        cfg.Name,
		Description: "Ouvrier worker generated by ouvrier new.",
		Events:      []string{workerManifestEvent(cfg)},
		Outcomes:    []string{workerManifestOutcome(cfg)},
		AdminURL:    "http://127.0.0.1:8080",
	}
	encoded, err := json.MarshalIndent(manifest, "", "  ")
	if err != nil {
		return "{}\n"
	}
	return string(encoded) + "\n"
}

func workerManifestEvent(cfg Config) string {
	switch cfg.trigger.kind {
	case triggerHTTP:
		return "http." + cfg.Trigger
	case triggerCron:
		return cfg.Trigger
	case triggerWebhook:
		return cfg.Trigger
	case triggerStream:
		return cfg.Trigger
	default:
		return cfg.Trigger
	}
}

func workerManifestOutcome(cfg Config) string {
	switch cfg.trigger.kind {
	case triggerHTTP:
		return "json_reply"
	default:
		return "log_sink"
	}
}

func envExample(cfg Config) string {
	var b strings.Builder
	for _, key := range envExampleVars(cfg) {
		b.WriteString(key)
		b.WriteString("=\n")
	}
	b.WriteString("OUVRIER_ENV=dev\n")
	b.WriteString("OUVRIER_ADDR=:8080\n")
	b.WriteString("OUVRIER_LOG_LEVEL=info\n")
	b.WriteString("OUVRIER_ADMIN_TOKEN=\n")
	return b.String()
}

func requiredEnvVars(cfg Config) []string {
	switch modelProvider(cfg.Model) {
	case "anthropic":
		return []string{"ANTHROPIC_API_KEY"}
	case "openai":
		return []string{"OPENAI_API_KEY"}
	case "mistral":
		return []string{"MISTRAL_API_KEY"}
	case "gemini":
		return []string{"GEMINI_API_KEY"}
	case "groq":
		return []string{"GROQ_API_KEY"}
	case "deepseek":
		return []string{"DEEPSEEK_API_KEY"}
	case "azure":
		return []string{"AZURE_OPENAI_API_KEY", "AZURE_OPENAI_BASE_URL"}
	case "bedrock":
		return []string{"AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY", "AWS_REGION"}
	default:
		return nil
	}
}

func envExampleVars(cfg Config) []string {
	switch modelProvider(cfg.Model) {
	case "ollama":
		return []string{"OLLAMA_BASE_URL"}
	case "vllm":
		return []string{"VLLM_BASE_URL", "VLLM_API_KEY"}
	default:
		return requiredEnvVars(cfg)
	}
}

func modelProvider(model string) string {
	provider, _, _ := strings.Cut(strings.TrimSpace(model), "/")
	return strings.ToLower(provider)
}

func gitignore() string {
	// .env* covers per-environment files like .env.staging and .env.prod;
	// the committed .env.example template is explicitly re-included.
	return `.env*
!.env.example
bin/
dist/
*.log
`
}

func readme(cfg Config) string {
	return fmt.Sprintf(`# %s

Minimal Ouvrier worker generated by `+"`ouvrier new`"+`.

## Run

1. Fill `+"`.env`"+` from `+"`.env.example`"+`.
2. Start the worker:

`+"```sh"+`
go run .
`+"```"+`

## Pipeline

- Trigger: `+"`%s`"+`
- Model: `+"`%s`"+`
- Output: %s
`, cfg.Name, cfg.Trigger, cfg.Model, readmeOutputLabel(cfg))
}

func readmeOutputLabel(cfg Config) string {
	switch cfg.trigger.kind {
	case triggerHTTP:
		return "JSON reply"
	default:
		return "Log sink"
	}
}
