package scaffold

import "fmt"

func mainGo(cfg Config) string {
	return fmt.Sprintf(`package main

import (
	"log"

	ovr %q
)

type ticketReply struct {
	Status string `+"`json:\"status\"`"+`
}

func main() {
	if err := ovr.Run(":8080",
		ovr.From(%q),
		ovr.Pipe("Handle the request and return a concise JSON status.",
			ovr.Model(%q),
		),
		ovr.Reply(ovr.JSON[ticketReply]()),
	); err != nil {
		log.Fatal(err)
	}
}
`, cfg.FrameworkModule, cfg.Trigger, cfg.Model)
}

func goMod(cfg Config) string {
	body := fmt.Sprintf(`module %s

go 1.25.0

require %s v0.0.0
`, cfg.Name, cfg.FrameworkModule)
	if cfg.FrameworkDir != "" {
		body += fmt.Sprintf(`
replace %s => %s
`, cfg.FrameworkModule, cfg.FrameworkDir)
	}
	return body
}

func pipYAML(cfg Config) string {
	return fmt.Sprintf(`name: %s
version: 0.1.0

deploy:
  ssh:
    host: ops@example.com
    path: /opt/%s
    service: %s.service
    healthcheck:
      path: /admin/health
      timeout: 30s
  docker:
    image: %s:0.1.0
    base: gcr.io/distroless/static-debian12

env:
  required:
    - ANTHROPIC_API_KEY

healthcheck:
  path: /admin/health
  interval: 30s
`, cfg.Name, cfg.Name, cfg.Name, cfg.Name)
}

func envExample() string {
	return `ANTHROPIC_API_KEY=
PIP_ENV=dev
PIP_PORT=8080
PIP_LOG_LEVEL=info
PIP_ADMIN_TOKEN=
`
}

func gitignore() string {
	return `.env
bin/
dist/
*.log
`
}

func readme(cfg Config) string {
	return fmt.Sprintf(`# %s

Minimal Ouvrier worker generated by `+"`ouvrier new`"+`.

## Run

1. Fill `+"`.env`"+` from `+"`.env.example`"+`.
2. Start the worker:

`+"```sh"+`
go run .
`+"```"+`

## Pipeline

- Trigger: `+"`%s`"+`
- Model: `+"`%s`"+`
- Output: JSON reply
`, cfg.Name, cfg.Trigger, cfg.Model)
}
