package scaffold

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func mainGo(cfg Config) string {
	replyType := ""
	if cfg.trigger.usesReplyType {
		replyType = "\ntype ticketReply struct {\n\tStatus string `json:\"status\"`\n}\n"
	}
	return fmt.Sprintf(`package main

import (
	"log"

	ovr %q
)
%s
func main() {
	if err := ovr.Run(":8080",
		ovr.From(%s),
		ovr.Pipe("Handle the event and return a concise status.",
			ovr.Model(%q),
		),
		%s,
	); err != nil {
		log.Fatal(err)
	}
}
`, cfg.FrameworkModule, replyType, cfg.trigger.fromArg, cfg.Model, cfg.trigger.terminalExpr)
}

func goMod(cfg Config) string {
	body := fmt.Sprintf(`module %s

go 1.25.0

require %s v0.0.0
`, cfg.Name, cfg.FrameworkModule)
	if requirements := frameworkRequireBlocks(cfg); requirements != "" {
		body += "\n" + requirements
	}
	if cfg.FrameworkDir != "" {
		body += fmt.Sprintf(`
replace %s => %s
`, cfg.FrameworkModule, cfg.FrameworkDir)
	}
	return body
}

func frameworkRequireBlocks(cfg Config) string {
	if cfg.FrameworkDir == "" {
		return ""
	}
	data, err := os.ReadFile(filepath.Join(cfg.FrameworkDir, "go.mod"))
	if err != nil {
		return ""
	}

	var blocks []string
	lines := strings.Split(string(data), "\n")
	for i := 0; i < len(lines); i++ {
		line := strings.TrimSpace(lines[i])
		switch {
		case strings.HasPrefix(line, "require ("):
			var block []string
			for ; i < len(lines); i++ {
				block = append(block, lines[i])
				if strings.TrimSpace(lines[i]) == ")" {
					break
				}
			}
			blocks = append(blocks, strings.Join(block, "\n"))
		case strings.HasPrefix(line, "require "):
			blocks = append(blocks, lines[i])
		}
	}
	return strings.Join(blocks, "\n\n")
}

func pipYAML(cfg Config) string {
	return fmt.Sprintf(`name: %s
version: 0.1.0

deploy:
  ssh:
    host: ops@example.com
    path: /opt/%s
    service: %s.service
    healthcheck:
      path: /admin/health
      timeout: 30s
  docker:
    image: %s:0.1.0
    base: gcr.io/distroless/static-debian12

env:
  required:
    - ANTHROPIC_API_KEY

healthcheck:
  path: /admin/health
  interval: 30s
`, cfg.Name, cfg.Name, cfg.Name, cfg.Name)
}

func envExample() string {
	return `ANTHROPIC_API_KEY=
PIP_ENV=dev
PIP_PORT=8080
PIP_LOG_LEVEL=info
PIP_ADMIN_TOKEN=
`
}

func gitignore() string {
	return `.env
bin/
dist/
*.log
`
}

func readme(cfg Config) string {
	return fmt.Sprintf(`# %s

Minimal Ouvrier worker generated by `+"`ouvrier new`"+`.

## Run

1. Fill `+"`.env`"+` from `+"`.env.example`"+`.
2. Start the worker:

`+"```sh"+`
go run .
`+"```"+`

## Pipeline

- Trigger: `+"`%s`"+`
- Model: `+"`%s`"+`
- Output: JSON reply
`, cfg.Name, cfg.Trigger, cfg.Model)
}
