package deploy

// sudoers.go renders the least-privilege sudoers snippet for the
// release-layout deploy flow (`ouvrier deploy ssh --print-sudoers`). The
// snippet enumerates exactly the privileged commands the deploy helpers in
// release.go and systemd_unit.go run — full paths, fixed arguments, no
// wildcards — so granting it is auditable line by line.

import (
	"fmt"
	"strings"
)

// SudoersParams parameterizes the rendered snippet.
type SudoersParams struct {
	// DeployUser is the unprivileged account the deploy logs in as over ssh.
	DeployUser string
	// Name is the worker name from pip.yaml (required).
	Name string
	// Service is the unit name (default ouvrier-<Name>; ".service" optional).
	Service string
	// Root is the remote install root (default /opt/ouvrier/<Name>).
	Root string
}

func (p SudoersParams) normalized() SudoersParams {
	if strings.TrimSpace(p.DeployUser) == "" {
		p.DeployUser = "deploy"
	}
	p.Service = CanonicalServiceName(p.Service)
	if p.Service == "" {
		p.Service = "ouvrier-" + p.Name
	}
	if p.Root == "" {
		p.Root = "/opt/ouvrier/" + p.Name
	}
	return p
}

// sudoCommandSpecs lists, in deploy order, the exact privileged commands the
// deploy flow runs, in the unquoted argv form sudoers matches against. This
// is the single source for SudoersSnippet; the command-helper tests assert
// each helper's `sudo` invocation matches one of these specs.
func sudoCommandSpecs(p SudoersParams) []string {
	svc := UnitUser(p.Name)
	unit := p.Service + ".service"
	return []string{
		// sudo -n probe (SudoProbeCommand).
		"/usr/bin/true",
		// First-deploy provisioning (CreateServiceUserCommand, MkdirLayoutCommands).
		fmt.Sprintf("/usr/sbin/useradd --system --home-dir %s --no-create-home --shell /usr/sbin/nologin %s", p.Root, svc),
		fmt.Sprintf("/usr/bin/install -d -m 0755 -o %s -- %s", p.DeployUser, p.Root),
		fmt.Sprintf("/usr/bin/install -d -m 0750 -o root -g %s -- %s/shared", svc, p.Root),
		fmt.Sprintf("/usr/bin/install -d -m 0750 -o %s -g %s -- %s/shared/state", svc, svc, p.Root),
		// Secrets promotion (InstallEnvCommands).
		fmt.Sprintf("/usr/bin/install -o root -g %s -m 0640 -- %s%s %s/shared/.env", svc, p.Root, envStageSuffix, p.Root),
		// Unit lifecycle (InstallUnitIfChangedCommand, Enable/Restart/Stop, JournalTail).
		fmt.Sprintf("/usr/bin/install -m 0644 -- %s/%s /etc/systemd/system/%s", p.Root, unit, unit),
		"/usr/bin/systemctl daemon-reload",
		"/usr/bin/systemctl enable " + unit,
		"/usr/bin/systemctl restart " + unit,
		"/usr/bin/systemctl stop " + unit,
		"/usr/bin/journalctl -u " + unit + " -n 50 --no-pager",
	}
}

// SudoersSnippet renders the sudoers fragment granting p.DeployUser exactly
// the privileged commands the deploy flow runs against this worker.
func SudoersSnippet(p SudoersParams) string {
	p = p.normalized()
	var b strings.Builder
	fmt.Fprintf(&b, `# Least-privilege sudoers for Ouvrier deploys of worker %q.
# Generated by: ouvrier deploy ssh --print-sudoers
# Install as /etc/sudoers.d/ouvrier-%s (mode 0440); validate with visudo -cf.
# Grants only the exact commands the deploy flow runs (unit %s.service, root %s).
`, p.Name, p.Name, p.Service, p.Root)
	for _, spec := range sudoCommandSpecs(p) {
		fmt.Fprintf(&b, "%s ALL=(root) NOPASSWD: %s\n", p.DeployUser, spec)
	}
	return b.String()
}
